### ISSUE TITLE
Empty droids

### ISSUE THREAD

**Issue by DanilaOleynik** [PanDAWMS/panda-yoda#12]
A test job was submitted with 4 nodes(1Yoda+3Droids, 16 cores per node, walltime 30 minutes), Yoda loaded 96 events.
Droid-1 got 48 events, processed 32 events
Droid-2 got 48 events, processed 36 events
Droid-3 got 0 events, waited 10 minutes and then quit(10 minutes is the time_out of Yoda reading event range files)
Three Droids ran from 09:28 to 09:58
All events were assigned between 09:28:40 and 09:28:52, in 12 seconds.
Droid-3 sent REQUEST_JOB at 09:28:27, but it didn’t get a job until 09:30:51(Droid-1 sent REQUEST_JOB at 09:28:40, Droid-2 sent REQUEST_JOB at 09:28:27), which was two minutes after all events were assigned.

**Comment by wguanicedew** [comment]
can closed
