### ISSUE TITLE
Yoda stuck without assaigning events to droids.

### ISSUE THREAD

**Issue by DanilaOleynik** [PanDAWMS/panda-yoda#7]
A test job was submitted with 3 nodes(1Yoda+2Droids, 16 cores per node, walltime 30 minutes), Yoda loaded 20000 events but then just waiting for more events, without assigning any events to droids. AthenaMP didn’t got any events to run in 30 minutes(it didn’t quit)

**Comment by wguanicedew** [comment]
can closed
